config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :questions, only: [:index, :show] do
    member do
      post 'check_answer'
    end
  end
  root 'questions#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/question.rb
class Question < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.find(params[:id])
    @result = params[:result]
  end

  def check_answer
    @question = Question.find(params[:id])
    user_answer = params[:answer].strip.downcase
    correct = user_answer == @question.correct_answer.strip.downcase
    result = correct ? 'Correct!' : 'Wrong, try again.'
    redirect_to question_path(@question, result: result)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>QuizApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/index.html.erb
<h1>Quiz Questions</h1>
<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.content, question_path(question) %></li>
  <% end %>
</ul>

app/views/questions/show.html.erb
<h1><%= @question.content %></h1>

<%= form_with url: check_answer_question_path(@question), method: :post do %>
  <%= text_field_tag :answer %>
  <%= submit_tag "Submit" %>
<% end %>
<% if @result.present? %>
  <p style="color: <%= @result == 'Correct!' ? 'green' : 'red' %>;"><%= @result %></p>
<% end %>

<%= link_to 'Back', questions_path %>